owner = "XAMPPRocky"
repo = "tokei"
from = "release:latest"
to = "today"
date-format = "%Y-%m-%d"
# skip-labels = ["dependencies"]

[[categories]]
title = "Compiler"
labels = ["T-compiler"]

[[includes]]
owner = "rust-lang"
repo = "rust"
use-parent-for-timeframe = true

[template]
string = """
Version {{version}} ({{date}})
============================

{% for title, prs in categories %}
{{ title }}
-----------------------

    {% for pr in prs %}
- [{{pr.title}}]({{pr.html_url}})
    {%- endfor %}
{% endfor %}

{% for data in includes %}
{{ data.title }}
-----------------------

    {% for pr in data.prs %}
- [{{pr.title}}]({{pr.html_url}})
    {%- endfor %}
{% endfor %}

UNSORTED
--------
{% for pr in prs -%}
- [{{pr.title}}]({{pr.html_url}})
{% endfor %}

{% for _, prs in categories %}
{% for pr in prs -%}
[{{pr.number}}]: {{pr.html_url}}
{% endfor %}
{%- endfor %}

{% for pr in prs -%}
[{{pr.number}}]: {{pr.html_url}}
{% endfor %}
"""

